version: '3.4'
services:
  jenkins_demo:
    image: IMAGE_LATEST
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    expose:
      - "80"
    ports:
      - 6001:80
